### ISSUE TITLE
Chunk/Snippet properties

### ISSUE THREAD

**Issue by pk-informatics** [craftsmancoding/repoman#24]
Hi,

Howto define chunk properties within the chunk docblock?

Kind regards,
pk

**Comment by fireproofsocks** [comment]
Ok, after studying this I finally implemented a solution: properties will be defined in-line in the DocBlock comments using the `@param` declaration.  In order to accomplish this, I extended the DocBlock syntax a bit further to cover default values and options.  This solution is relatively straight-forward for the developer and it will lead to better code documentation, so I think it is a win-win.

To implement properties, simply declare `@param` in your DocBlock, e.g. :

````
@param textfield $tpl Choose a chunk. default=MyChunk
@param list $choose A dropdown default=int options={"str":"String","int":"Integer"}
````

The "default" bit defines the value of the property (i.e. the default value).  The "options" can be used to specify an JSON hash (or a JSON array) in the format "value":"text".

I will add a tutorial demonstrating this.


525e288..4c78aa2  master -> master
