### ISSUE TITLE
[Q] Is there a possibility of having packages folder out of web root?

### ISSUE THREAD

**Issue by zaigham** [craftsmancoding/repoman#30]
Kindly assist.
Thanks.
![screenshot_052315_114621_am](https://cloud.githubusercontent.com/assets/114390/7782758/7c23184c-0141-11e5-9423-c5fa240a50ee.jpg)

**Comment by fireproofsocks** [comment]
It's not currently possible, but this is by design: a Modx package includes both PHP and web assets. Because web assets have to be in the web folder, the package must also be in the web folder. Once you build and distribute the package in the MODx format, then the files get installed in 2 locations and the PHP files can exist above web root (along with the core directory).

I have considered is a "publish" command that would take a package's assets folder and copy it to the assets_dir location. However that would make development much more difficult: you would have to remember to copy the live assets back into your version controlled directory. 

Since repoman's goal is to simplify dev, I have not implemented that workflow.

**Comment by zaigham** [comment]
That makes sense. :smile: 

Thanks for detailed response, much appreciated. :+1:
